routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\UsersController::class, 'index'])->middleware('auth');

Route::resource('users', \App\Http\Controllers\UsersController::class)->middleware('auth')->only(['show', 'index']);
Route::resource('posts', \App\Http\Controllers\PostsController::class)->middleware('auth');
Route::resource('posts.comments', \App\Http\Controllers\CommentsController::class)->middleware('auth')->only(['store']);
Route::resource('posts.likes', \App\Http\Controllers\LikesController::class)->middleware('auth')->only(['store']);

Route::post('users.follow', [\App\Http\Controllers\UsersController::class, 'followUser'])->middleware('auth')->name('users.follow');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return BelongsToMany
     */
    public function users() {
        return $this->belongsToMany(User::class, 'users_users', 'follower_id', 'following_id');
    }

    /**
     * @return HasMany
     */
    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    /**
     * @return HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return HasMany
     */
    public function likes()
    {
        return $this->hasMany(Like::class);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View|Response
     */
    public function index()
    {
        $all_users = User::all();
        $user = Auth::user();
        $subs = $user->users;
        return view('users.index', compact('user', 'subs', 'all_users'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return Factory|View|Response
     */
    public function show(User $user)
    {
        return view('users.show', compact('user'));
    }

    /**
     * @return int
     */
    static function followersCount()
    {
        $user = Auth::user();
        $count = 0;
        foreach ($user->users as $item){
            if ($item->follower_id = $user->id){
                $count += 1;
            }
        }
        return $count;
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function followUser(Request $request)
    {
        $user = Auth::user();
        if (!$user->users()->where('follower_id', $user->id)->where('following_id', $request->input('user_id'))->exists()){
            $auth_user = Auth::user();
            $auth_user->users()->attach($request->input('user_id'));
        } else {
            $auth_user = Auth::user();
            $auth_user->users()->detach($request->input('user_id'));
        }
        return redirect()->back();
    }

    /**
     * @param $all_users
     * @return |null
     */
    static function randomUser($all_users)
    {
        $count = count($all_users);
        if ($count>0){
            $random_user = $all_users->find(rand(1, $count));
            return $random_user;
        }
        return NULL;
    }
}

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')

    <h1>Your Feed:</h1>

    @foreach($subs as $sub)

        @foreach($sub->posts->sortBy('created_at') as $post)

            <h4>
                <a href="{{route('users.show', ['user' => $post->user->id])}}">{{$post->user->name}}</a>
            </h4>

            <div class="card mb-3" style="max-width: 500px">
                <a href="{{route('posts.show', ['post' => $post])}}">
                    <img class="w-100" src="{{asset('/storage/' . $post->photo)}}" alt="{{asset('/storage/' . $post->photo)}}"></a>
                <div class="card-body">
                    <h5 class="card-title">{{$post->title}}</h5>
                    <p class="card-text">{{$post->description}}</p>
                    <p class="card-text">Likes: {{$post->likes->pluck('like')->sum()}}</p>
                </div>
                @if(\App\Models\Like::where('user_id', $user->id)->where('post_id', $post->id)->exists())
                    @if(\App\Models\Like::where('user_id', $user->id)->where('post_id', $post->id)->get()->first()->like == true)
                        <div class="ml-auto mr-4">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
                                <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
                            </svg>
                        </div>
                    @endif
                @endif
                <div>
                    <form action="{{route('posts.likes.store', ['post' => $post])}}" method="post">
                        @csrf
                        <input type="hidden" name="post_id" value="{{$post->id}}">
                        <button class="btn btn-outline-info ml-2 mb-2" type="submit">Like</button>
                    </form>
                </div>

                <div>
                    <a class="btn btn-outline-info ml-2 mb-2" href="{{route('posts.show', ['post' => $post])}}">Show comments</a>
                </div>
            </div>

        @endforeach

    @endforeach
    <br>
    <hr>

    @if (!is_null(\App\Http\Controllers\UsersController::randomUser($all_users)))

        <a href="{{route('users.show', ['user' => \App\Http\Controllers\UsersController::randomUser($all_users)])}}"><h5>Watch random User</h5></a>

    @endif

@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')

    <h1>{{$user->name}}</h1>
    <form action="{{route('users.follow')}}" method="post">
        @csrf
        <input type="hidden" name="user_id" value="{{$user->id}}">
        <button class="btn btn-outline-primary" type="submit">Follow/Unfollow</button>
    </form>
    <br>
    <h5>Follows: {{$user->users->count()}}</h5>
    <h5>Followers: {{\App\Http\Controllers\UsersController::followersCount()}}</h5>

    @if ($user->id == \Illuminate\Support\Facades\Auth::user()->id)

        <a href="{{route('posts.index')}}">Edit my posts</a>

    @endif

    <br>

    <a href="{{route('posts.create')}}">Create new post</a>

    <br>
    <br>

    <h3>Posts:</h3>
    <div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach($user->posts as $post)
            <a href="{{route('posts.show', ['post' => $post])}}">
                <img class="col mb-1" src="{{asset('/storage/' . $post->photo)}}" alt="{{asset('/storage/' . $post->photo)}}"></a>
    @endforeach
    </div>

@endsection