routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\UsersController::class, 'index'])->middleware('auth');

Route::resource('users', \App\Http\Controllers\UsersController::class)->middleware('auth')->only(['show', 'index']);
Route::resource('posts', \App\Http\Controllers\PostsController::class)->middleware('auth');
Route::resource('posts.comments', \App\Http\Controllers\CommentsController::class)->middleware('auth')->only(['store']);
Route::resource('posts.likes', \App\Http\Controllers\LikesController::class)->middleware('auth')->only(['store']);

Route::post('users.follow', [\App\Http\Controllers\UsersController::class, 'followUser'])->middleware('auth')->name('users.follow');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Post extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'description', 'photo', 'user_id'];

    /**
     * @return BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * @return HasMany
     */
    public function likes()
    {
        return $this->hasMany(Like::class);
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PostRequest;
use App\Models\Post;
use App\Models\User;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View|void
     */
    public function index()
    {
        $user = Auth::user();
        $posts = $user->posts;
        return view('posts.index', compact('posts', 'user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View|Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param PostRequest $request
     * @return RedirectResponse|Response
     */
    public function store(PostRequest $request)
    {
        $post = new Post($request->all());
        $post->user()->associate($request->user());
        if ($request->hasFile('photo')) {
            $post->photo = $request->file('photo')->store('photos', 'public');
        }
        $post->save();
        return redirect()->route('posts.index')->with('success', 'Post created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post $post
     * @return Factory|View|Response
     */
    public function show(Post $post)
    {
        $user = Auth::user();
        return view('posts.show', compact('post', 'user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return Factory|View|Response
     */
    public function edit(Post $post)
    {
        return view('posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param PostRequest $request
     * @param \App\Models\Post $post
     * @return RedirectResponse|Response
     */
    public function update(PostRequest $request, Post $post)
    {
        $data = $request->all();
        if ($request->hasFile('photo')){
            $path = $request->file('photo')->store('photos', 'public');
            $data['photo'] = $path;
        }
        $post->user()->associate($request->user());
        $post->update($data);
        return redirect()->route('posts.index')->with('success', 'Post updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return RedirectResponse|Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect()->route('posts.index')->with('success', 'Post deleted!');
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')

    <form enctype="multipart/form-data" action="{{route('posts.store')}}" method="post">
        @csrf

        <div class="row mb-3">
            <label for="title" class="col-form-label">Title</label>
            <div class="col-sm-6">
                <input type="text" class="form-control" id="title" name="title">
            </div>
            @error('title')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="row mb-3">
            <label for="description" class="col-form-label">Description</label>
            <div class="col-sm-6">
                <textarea class="form-control" name="description" id="description"></textarea>
            </div>
            @error('description')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <br>

        <div class="row mb-3">
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="photo" name="photo">
                <label class="custom-file-label" for="photo">Choose photo</label>
            </div>
            @error('photo')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')

    <form enctype="multipart/form-data" action="{{route('posts.update', ['post' => $post])}}" method="post">
        @csrf
        @method('put')

        <div class="row mb-3">
            <label for="title" class="col-form-label">Title</label>
            <div class="col-sm-6">
                <input type="text" class="form-control" id="title" name="title" value="{{$post->title}}">
            </div>
            @error('title')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="row mb-3">
            <label for="description" class="col-form-label">Description</label>
            <div class="col-sm-6">
                <textarea class="form-control" name="description" id="description">{{$post->description}}</textarea>
            </div>
            @error('description')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <br>

        <img src="{{asset('/storage/' . $post->photo)}}" alt="{{$post->photo}}" style="width:100px;height:100px;"><br/><br>

        <div class="row mb-3">
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="photo" name="photo">
                <label class="custom-file-label" for="photo">Choose photo</label>
            </div>
            @error('photo')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>

        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')

    <h1>Your posts {{$user->name}}:</h1>


    @if($posts->count()>0)


        @foreach($posts as $post)
            <div class="card mb-3" style="max-width: 500px">
                <a href="{{route('posts.show', ['post' => $post])}}">
                    <img class="w-100" src="{{asset('/storage/' . $post->photo)}}" alt="{{asset('/storage/' . $post->photo)}}"></a>
                <div class="card-body">
                    <h5 class="card-title">{{$post->title}}</h5>
                    <p class="card-text">{{$post->description}}</p>
                    <p class="card-text">Likes: {{$post->likes->pluck('like')->sum()}}</p>
                </div>
                @if(\App\Models\Like::where('user_id', $user->id)->where('post_id', $post->id)->exists())
                    @if(\App\Models\Like::where('user_id', $user->id)->where('post_id', $post->id)->get()->first()->like == true)
                        <div class="ml-auto mr-4">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
                                <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
                            </svg>
                        </div>
                    @endif
                @endif
                <div>
                    <form action="{{route('posts.likes.store', ['post' => $post])}}" method="post">
                        @csrf
                        <input type="hidden" name="post_id" value="{{$post->id}}">
                        <button class="btn btn-outline-info ml-2 mb-2" type="submit">Like</button>
                    </form>
                </div>
                <a class="btn btn-outline-warning col-3 mb-1" href="{{route('posts.edit', ['post' => $post])}}">Edit</a>
                <div>
                    <a class="btn btn-outline-info" href="{{route('posts.show', ['post' => $post])}}">Show comments</a>
                </div>
            </div>

        @endforeach


    @else

    <p>No posts</p>

    @endif

@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')

    <h1>{{$post->user->name}}</h1>

    <div class="card mb-3" style="max-width: 500px">
        <img src="{{asset('/storage/' . $post->photo)}}" alt="{{asset('/storage/' . $post->photo)}}">
        <div class="card-body">
            <h5 class="card-title">{{$post->title}}</h5>
            <p class="card-text">{{$post->description}}</p>
            <p class="card-text">Likes: {{$post->likes->pluck('like')->sum()}}</p>
        </div>
        @if(\App\Models\Like::where('user_id', $user->id)->where('post_id', $post->id)->exists())
            @if(\App\Models\Like::where('user_id', $user->id)->where('post_id', $post->id)->get()->first()->like == true)
                <div class="ml-auto mr-4">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
                        <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
                    </svg>
                </div>
            @endif
        @endif
        <div>
            <form action="{{route('posts.likes.store', ['post' => $post])}}" method="post">
                @csrf
                <input type="hidden" name="post_id" value="{{$post->id}}">
                <button class="btn btn-outline-info ml-2 mb-2" type="submit">Like</button>
            </form>
        </div>
    </div>

    <h3>Comments: </h3>
    <br>

    <p>
        <a class="btn btn-primary" data-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Create comment</a>
    </p>
    <div class="row">
        <div class="col">
            <div class="collapse multi-collapse" id="multiCollapseExample1">
                <div class="card card-body">
                    <form action="{{route('posts.comments.store', ['post' => $post])}}" id="create-comment" method="post">
                        @csrf
                        <input type="hidden" id="post_id" value="{{$post->id}}">
                        <div class="form-group">
                            <label for="body">Comment</label>
                            <textarea name="body" class="form-control" id="body" rows="3" required></textarea>
                        </div>
                        <button id="create-comment-btn" type="submit" class="btn btn-outline-success">Add new
                            comment
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br>

    <div class="all-comments">
        @foreach($post->comments as $comment)

            <div id="comment-{{$comment->id}}" class="border mb-1 p-1">
                <h5>{{$comment->user->name}}</h5>
                <p>{{$comment->body}}</p>
            </div>

        @endforeach
    </div>

@endsection